name: Facebook Ad Budget Adjuster

on:
  schedule:
    - cron: ${{ secrets.MORNING_SCHEDULE }}
    - cron: ${{ secrets.EVENING_SCHEDULE }}
  workflow_dispatch:  # Allows manual triggering

jobs:
  adjust_budget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run budget adjuster
      env:
        FB_APP_ID: ${{ secrets.FB_APP_ID }}
        FB_APP_SECRET: ${{ secrets.FB_APP_SECRET }}
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
        AD_ACCOUNT_ID: ${{ secrets.AD_ACCOUNT_ID }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: python fb_ad_budget_adjuster/adjuster.py